version: "3.9"
services:
  mysql:
    image: mysql
    volumes:
      - mysqlvolume:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"

volumes:
  mysqlvolume:
